name: "[Storm] Deploy Golang API"

on:
  push:
    branches:
      - main

jobs:
  storm:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install storm
        run: |
          curl -fsSL https://raw.githubusercontent.com/Overal-X/formatio.storm/main/scripts/install.sh | bash
          echo "~/.storm/bin" >> $GITHUB_PATH

      - name: Show storm version
        run: storm version

      - name: Sub env variables to config files
        run: |
          export GITHUB_TOKEN=${{ secrets.GITHUB_TOKEN }}
          export GITHUB_REPO=${{ github.repository }}
          export GITHUB_REF=${{ github.ref_name }}
          envsubst < .storm/workflow.yaml > .storm/workflow-temp.yaml
          mv .storm/workflow-temp.yaml .storm/workflow.yaml

      - name: Install storm on remote servers
        run: |
          echo "${{ secrets.SSH_KEY }}" > "./id_rsa"
          storm agent install -i .storm/inventory.yaml -m prod

      - name: Run storm workflow
        run: |
          echo "${{ secrets.SSH_KEY }}" > "./id_rsa"
          storm agent run -i .storm/inventory.yaml .storm/workflow.yaml
